# _config.yml

# Site settings
title: Evelyn Pomasqui
description: Some friends call me "the eternal student of the universe"—a fancy way of saying I'm always learning or striving to learn something new. In other words, I'm a knowledge seeker who eagerly embraces any opportunity to dive into new insights.
baseurl: "" # the subpath of your site, e.g. /blog
url: "evepp.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
